# Controllers
from control.controller.DailyMenuController import DailyMenuController
from control.controller.EdibleController import EdibleController
from control.controller.FeedbackController import FeedbackController
from control.controller.RestaurantController import RestaurantController
from control.controller.UserController import StudentController, AdministratorController