from control.controller.Controller import Controller
from control.controller.EdibleController import EdibleController
from control.controller.DailyMenuController import DailyMenuController
from control.controller.UserController import UserController
from control.controller.RestaurantController import RestaurantController